/* *********************************************************************
 * This Original Work is copyright of 51 Degrees Mobile Experts Limited.
 * Copyright 2026 51 Degrees Mobile Experts Limited, Davidson House,
 * Forbury Square, Reading, Berkshire, United Kingdom RG1 3EU.
 *
 * This Original Work is licensed under the European Union Public Licence
 * (EUPL) v.1.2 and is subject to its terms as set out below.
 *
 * If a copy of the EUPL was not distributed with this file, You can obtain
 * one at https://opensource.org/licenses/EUPL-1.2.
 *
 * The 'Compatible Licences' set out in the Appendix to the EUPL (as may be
 * amended by the European Commission) shall be deemed incompatible for
 * the purposes of the Work and the provisions of the compatibility
 * clause in Article 5 of the EUPL shall not apply.
 *
 * If using the Work as, or as part of, a network application, by
 * including the attribution notice(s) required under Article 5 of the EUPL
 * in the end user terms of the application under an appropriate heading,
 * such notice(s) shall fulfill the requirements of that article.
 * ********************************************************************* */

/*
 * Symbol namespace for this crate's private copy of common-cxx.
 *
 * The IP Intelligence engine compiles its own copy of the shared common-cxx C
 * sources with FIFTYONE_DEGREES_LARGE_DATA_FILE_SUPPORT, which widens the file
 * offset types to 64 bit. Device Detection links a separate copy of the same
 * common-cxx through fiftyone-common-sys built with 32 bit offsets. The two
 * copies export the same fiftyoneDegrees* C symbols at incompatible ABIs, so a
 * binary that links both engines would let the linker bind each duplicated
 * symbol to a single definition, leaving one engine reading its data through
 * the wrong, ABI incompatible common code.
 *
 * This header is force included into every IP Intelligence translation unit
 * (see build.rs). It rewrites each shared common-cxx symbol to an ipi_ prefixed
 * name at preprocess time, so both the definitions in this crate's common-cxx
 * objects and every call site that references them are renamed together. Device
 * Detection keeps the unprefixed names, so the two copies no longer collide and
 * both engines work in one binary.
 *
 * Only the common-cxx symbols shared with the Device Detection common build are
 * renamed. The IP Intelligence engine surface (fiftyoneDegreesIpi*,
 * fiftyoneDegreesResultsIpi*, the weighted value collection and this crate's
 * shim helpers) is unique to this library, does not collide with anything, and
 * is left unprefixed so the Rust bindings keep calling it by its public name.
 *
 * This list is derived from the intersection of the common-cxx symbols defined
 * by fiftyone-common-c (the Device Detection common build) and the symbols the
 * IP Intelligence build defines or references. Regenerate it by dumping the
 * symbols of both static libraries (dumpbin /SYMBOLS) and intersecting the
 * External, defined fiftyoneDegrees* names with the names the IP Intelligence
 * build touches, excluding the fiftyoneDegreesIpi* engine surface.
 */

#ifndef FIFTYONE_DEGREES_IPI_SYMBOL_PREFIX_H
#define FIFTYONE_DEGREES_IPI_SYMBOL_PREFIX_H
#define fiftyoneDegreesBoolToInt ipi_fiftyoneDegreesBoolToInt
#define fiftyoneDegreesCacheCreate ipi_fiftyoneDegreesCacheCreate
#define fiftyoneDegreesCacheFree ipi_fiftyoneDegreesCacheFree
#define fiftyoneDegreesCacheGet ipi_fiftyoneDegreesCacheGet
#define fiftyoneDegreesCacheHash32 ipi_fiftyoneDegreesCacheHash32
#define fiftyoneDegreesCacheHash64 ipi_fiftyoneDegreesCacheHash64
#define fiftyoneDegreesCacheRelease ipi_fiftyoneDegreesCacheRelease
#define fiftyoneDegreesCollectionBinarySearch ipi_fiftyoneDegreesCollectionBinarySearch
#define fiftyoneDegreesCollectionCreateFromFile ipi_fiftyoneDegreesCollectionCreateFromFile
#define fiftyoneDegreesCollectionCreateFromMemory ipi_fiftyoneDegreesCollectionCreateFromMemory
#define fiftyoneDegreesCollectionGetInteger32 ipi_fiftyoneDegreesCollectionGetInteger32
#define fiftyoneDegreesCollectionGetIsMemoryOnly ipi_fiftyoneDegreesCollectionGetIsMemoryOnly
#define fiftyoneDegreesCollectionHeaderFromFile ipi_fiftyoneDegreesCollectionHeaderFromFile
#define fiftyoneDegreesCollectionHeaderFromMemory ipi_fiftyoneDegreesCollectionHeaderFromMemory
#define fiftyoneDegreesCollectionReadFileFixed ipi_fiftyoneDegreesCollectionReadFileFixed
#define fiftyoneDegreesCollectionReadFilePosition ipi_fiftyoneDegreesCollectionReadFilePosition
#define fiftyoneDegreesCollectionReadFileVariable ipi_fiftyoneDegreesCollectionReadFileVariable
#define fiftyoneDegreesComponentGetDefaultProfileId ipi_fiftyoneDegreesComponentGetDefaultProfileId
#define fiftyoneDegreesComponentGetFinalSize ipi_fiftyoneDegreesComponentGetFinalSize
#define fiftyoneDegreesComponentGetHeaders ipi_fiftyoneDegreesComponentGetHeaders
#define fiftyoneDegreesComponentGetKeyValuePair ipi_fiftyoneDegreesComponentGetKeyValuePair
#define fiftyoneDegreesComponentGetName ipi_fiftyoneDegreesComponentGetName
#define fiftyoneDegreesComponentInitList ipi_fiftyoneDegreesComponentInitList
#define fiftyoneDegreesComponentReadFromFile ipi_fiftyoneDegreesComponentReadFromFile
#define fiftyoneDegreesConvertWkbToWkt ipi_fiftyoneDegreesConvertWkbToWkt
#define fiftyoneDegreesDataMalloc ipi_fiftyoneDegreesDataMalloc
#define fiftyoneDegreesDataReset ipi_fiftyoneDegreesDataReset
#define fiftyoneDegreesDataSetFree ipi_fiftyoneDegreesDataSetFree
#define fiftyoneDegreesDataSetGet ipi_fiftyoneDegreesDataSetGet
#define fiftyoneDegreesDataSetInitFromFile ipi_fiftyoneDegreesDataSetInitFromFile
#define fiftyoneDegreesDataSetInitHeaders ipi_fiftyoneDegreesDataSetInitHeaders
#define fiftyoneDegreesDataSetInitInMemory ipi_fiftyoneDegreesDataSetInitInMemory
#define fiftyoneDegreesDataSetInitProperties ipi_fiftyoneDegreesDataSetInitProperties
#define fiftyoneDegreesDataSetRelease ipi_fiftyoneDegreesDataSetRelease
#define fiftyoneDegreesDataSetReloadManagerFromFile ipi_fiftyoneDegreesDataSetReloadManagerFromFile
#define fiftyoneDegreesDataSetReloadManagerFromMemory ipi_fiftyoneDegreesDataSetReloadManagerFromMemory
#define fiftyoneDegreesDataSetReset ipi_fiftyoneDegreesDataSetReset
#define fiftyoneDegreesEvidenceAddPair ipi_fiftyoneDegreesEvidenceAddPair
#define fiftyoneDegreesEvidenceAddString ipi_fiftyoneDegreesEvidenceAddString
#define fiftyoneDegreesEvidenceCreate ipi_fiftyoneDegreesEvidenceCreate
#define fiftyoneDegreesEvidenceFree ipi_fiftyoneDegreesEvidenceFree
#define fiftyoneDegreesEvidenceIterate ipi_fiftyoneDegreesEvidenceIterate
#define fiftyoneDegreesEvidenceIterateForHeaders ipi_fiftyoneDegreesEvidenceIterateForHeaders
#define fiftyoneDegreesEvidenceMapPrefix ipi_fiftyoneDegreesEvidenceMapPrefix
#define fiftyoneDegreesEvidencePrefixString ipi_fiftyoneDegreesEvidencePrefixString
#define fiftyoneDegreesExceptionCheckAndExit ipi_fiftyoneDegreesExceptionCheckAndExit
#define fiftyoneDegreesExceptionGetMessage ipi_fiftyoneDegreesExceptionGetMessage
#define fiftyoneDegreesFileAddTempFileName ipi_fiftyoneDegreesFileAddTempFileName
#define fiftyoneDegreesFileCopy ipi_fiftyoneDegreesFileCopy
#define fiftyoneDegreesFileCreateDirectory ipi_fiftyoneDegreesFileCreateDirectory
#define fiftyoneDegreesFileCreateTempFile ipi_fiftyoneDegreesFileCreateTempFile
#define fiftyoneDegreesFileDelete ipi_fiftyoneDegreesFileDelete
#define fiftyoneDegreesFileDeleteUnusedTempFiles ipi_fiftyoneDegreesFileDeleteUnusedTempFiles
#define fiftyoneDegreesFileGetBaseName ipi_fiftyoneDegreesFileGetBaseName
#define fiftyoneDegreesFileGetExistingTempFile ipi_fiftyoneDegreesFileGetExistingTempFile
#define fiftyoneDegreesFileGetFileName ipi_fiftyoneDegreesFileGetFileName
#define fiftyoneDegreesFileGetPath ipi_fiftyoneDegreesFileGetPath
#define fiftyoneDegreesFileGetSize ipi_fiftyoneDegreesFileGetSize
#define fiftyoneDegreesFileHandleGet ipi_fiftyoneDegreesFileHandleGet
#define fiftyoneDegreesFileHandleRelease ipi_fiftyoneDegreesFileHandleRelease
#define fiftyoneDegreesFileNewTempFile ipi_fiftyoneDegreesFileNewTempFile
#define fiftyoneDegreesFileOpen ipi_fiftyoneDegreesFileOpen
#define fiftyoneDegreesFilePoolInit ipi_fiftyoneDegreesFilePoolInit
#define fiftyoneDegreesFilePoolRelease ipi_fiftyoneDegreesFilePoolRelease
#define fiftyoneDegreesFilePoolReset ipi_fiftyoneDegreesFilePoolReset
#define fiftyoneDegreesFileReadToByteArray ipi_fiftyoneDegreesFileReadToByteArray
#define fiftyoneDegreesFileSeek ipi_fiftyoneDegreesFileSeek
#define fiftyoneDegreesFileTell ipi_fiftyoneDegreesFileTell
#define fiftyoneDegreesFileWrite ipi_fiftyoneDegreesFileWrite
#define fiftyoneDegreesFloatIsEqual ipi_fiftyoneDegreesFloatIsEqual
#define fiftyoneDegreesFloatToNative ipi_fiftyoneDegreesFloatToNative
#define fiftyoneDegreesFree ipi_fiftyoneDegreesFree
#define fiftyoneDegreesFreeAligned ipi_fiftyoneDegreesFreeAligned
#define fiftyoneDegreesGetCollectionKeyTypeForStoredValueType ipi_fiftyoneDegreesGetCollectionKeyTypeForStoredValueType
#define fiftyoneDegreesHeaderGetIndex ipi_fiftyoneDegreesHeaderGetIndex
#define fiftyoneDegreesHeadersCreate ipi_fiftyoneDegreesHeadersCreate
#define fiftyoneDegreesHeadersFree ipi_fiftyoneDegreesHeadersFree
#define fiftyoneDegreesHeadersGetHeaderFromUniqueId ipi_fiftyoneDegreesHeadersGetHeaderFromUniqueId
#define fiftyoneDegreesHeadersIsHttp ipi_fiftyoneDegreesHeadersIsHttp
#define fiftyoneDegreesIndicesPropertyProfileCreate ipi_fiftyoneDegreesIndicesPropertyProfileCreate
#define fiftyoneDegreesIndicesPropertyProfileFree ipi_fiftyoneDegreesIndicesPropertyProfileFree
#define fiftyoneDegreesIndicesPropertyProfileLookup ipi_fiftyoneDegreesIndicesPropertyProfileLookup
#define fiftyoneDegreesIntToBool ipi_fiftyoneDegreesIntToBool
#define fiftyoneDegreesIpAddressesCompare ipi_fiftyoneDegreesIpAddressesCompare
#define fiftyoneDegreesIpAddressParse ipi_fiftyoneDegreesIpAddressParse
#define fiftyoneDegreesJsonDocumentEnd ipi_fiftyoneDegreesJsonDocumentEnd
#define fiftyoneDegreesJsonDocumentStart ipi_fiftyoneDegreesJsonDocumentStart
#define fiftyoneDegreesJsonPropertyEnd ipi_fiftyoneDegreesJsonPropertyEnd
#define fiftyoneDegreesJsonPropertySeparator ipi_fiftyoneDegreesJsonPropertySeparator
#define fiftyoneDegreesJsonPropertyStart ipi_fiftyoneDegreesJsonPropertyStart
#define fiftyoneDegreesJsonPropertyValues ipi_fiftyoneDegreesJsonPropertyValues
#define fiftyoneDegreesListAdd ipi_fiftyoneDegreesListAdd
#define fiftyoneDegreesListFree ipi_fiftyoneDegreesListFree
#define fiftyoneDegreesListGetAsString ipi_fiftyoneDegreesListGetAsString
#define fiftyoneDegreesListInit ipi_fiftyoneDegreesListInit
#define fiftyoneDegreesListRelease ipi_fiftyoneDegreesListRelease
#define fiftyoneDegreesListReset ipi_fiftyoneDegreesListReset
#define fiftyoneDegreesMalloc ipi_fiftyoneDegreesMalloc
#define fiftyoneDegreesMallocAligned ipi_fiftyoneDegreesMallocAligned
#define fiftyoneDegreesMemoryAdvance ipi_fiftyoneDegreesMemoryAdvance
#define fiftyoneDegreesMemoryStandardFree ipi_fiftyoneDegreesMemoryStandardFree
#define fiftyoneDegreesMemoryStandardFreeAligned ipi_fiftyoneDegreesMemoryStandardFreeAligned
#define fiftyoneDegreesMemoryStandardMalloc ipi_fiftyoneDegreesMemoryStandardMalloc
#define fiftyoneDegreesMemoryStandardMallocAligned ipi_fiftyoneDegreesMemoryStandardMallocAligned
#define fiftyoneDegreesMemoryTrackingFree ipi_fiftyoneDegreesMemoryTrackingFree
#define fiftyoneDegreesMemoryTrackingFreeAligned ipi_fiftyoneDegreesMemoryTrackingFreeAligned
#define fiftyoneDegreesMemoryTrackingGetAllocated ipi_fiftyoneDegreesMemoryTrackingGetAllocated
#define fiftyoneDegreesMemoryTrackingGetMax ipi_fiftyoneDegreesMemoryTrackingGetMax
#define fiftyoneDegreesMemoryTrackingMalloc ipi_fiftyoneDegreesMemoryTrackingMalloc
#define fiftyoneDegreesMemoryTrackingMallocAligned ipi_fiftyoneDegreesMemoryTrackingMallocAligned
#define fiftyoneDegreesMemoryTrackingReset ipi_fiftyoneDegreesMemoryTrackingReset
#define fiftyoneDegreesNativeToFloat ipi_fiftyoneDegreesNativeToFloat
#define fiftyoneDegreesOverrideHasValueForRequiredPropertyIndex ipi_fiftyoneDegreesOverrideHasValueForRequiredPropertyIndex
#define fiftyoneDegreesOverrideProfileIds ipi_fiftyoneDegreesOverrideProfileIds
#define fiftyoneDegreesOverridePropertiesCreate ipi_fiftyoneDegreesOverridePropertiesCreate
#define fiftyoneDegreesOverridePropertiesFree ipi_fiftyoneDegreesOverridePropertiesFree
#define fiftyoneDegreesOverridesAdd ipi_fiftyoneDegreesOverridesAdd
#define fiftyoneDegreesOverridesExtractFromEvidence ipi_fiftyoneDegreesOverridesExtractFromEvidence
#define fiftyoneDegreesOverridesGetOverridingRequiredPropertyIndex ipi_fiftyoneDegreesOverridesGetOverridingRequiredPropertyIndex
#define fiftyoneDegreesOverrideValuesAdd ipi_fiftyoneDegreesOverrideValuesAdd
#define fiftyoneDegreesOverrideValuesCreate ipi_fiftyoneDegreesOverrideValuesCreate
#define fiftyoneDegreesOverrideValuesFree ipi_fiftyoneDegreesOverrideValuesFree
#define fiftyoneDegreesOverrideValuesGetFirst ipi_fiftyoneDegreesOverrideValuesGetFirst
#define fiftyoneDegreesOverrideValuesReset ipi_fiftyoneDegreesOverrideValuesReset
#define fiftyoneDegreesPoolFree ipi_fiftyoneDegreesPoolFree
#define fiftyoneDegreesPoolInit ipi_fiftyoneDegreesPoolInit
#define fiftyoneDegreesPoolItemGet ipi_fiftyoneDegreesPoolItemGet
#define fiftyoneDegreesPoolItemRelease ipi_fiftyoneDegreesPoolItemRelease
#define fiftyoneDegreesPoolReset ipi_fiftyoneDegreesPoolReset
#define fiftyoneDegreesProcessGetId ipi_fiftyoneDegreesProcessGetId
#define fiftyoneDegreesProfileGetByIndex ipi_fiftyoneDegreesProfileGetByIndex
#define fiftyoneDegreesProfileGetByProfileId ipi_fiftyoneDegreesProfileGetByProfileId
#define fiftyoneDegreesProfileGetByProfileIdIndirect ipi_fiftyoneDegreesProfileGetByProfileIdIndirect
#define fiftyoneDegreesProfileGetFinalSize ipi_fiftyoneDegreesProfileGetFinalSize
#define fiftyoneDegreesProfileGetOffsetForProfileId ipi_fiftyoneDegreesProfileGetOffsetForProfileId
#define fiftyoneDegreesProfileIterateProfilesForPropertyAndValue ipi_fiftyoneDegreesProfileIterateProfilesForPropertyAndValue
#define fiftyoneDegreesProfileIterateProfilesForPropertyWithTypeAndValue ipi_fiftyoneDegreesProfileIterateProfilesForPropertyWithTypeAndValue
#define fiftyoneDegreesProfileIterateProfilesForPropertyWithTypeAndValueAndOffsetExtractor ipi_fiftyoneDegreesProfileIterateProfilesForPropertyWithTypeAndValueAndOffsetExtractor
#define fiftyoneDegreesProfileIterateValueIndexes ipi_fiftyoneDegreesProfileIterateValueIndexes
#define fiftyoneDegreesProfileIterateValuesForProperty ipi_fiftyoneDegreesProfileIterateValuesForProperty
#define fiftyoneDegreesProfileIterateValuesForPropertyWithIndex ipi_fiftyoneDegreesProfileIterateValuesForPropertyWithIndex
#define fiftyoneDegreesProfileOffsetAsPureOffset ipi_fiftyoneDegreesProfileOffsetAsPureOffset
#define fiftyoneDegreesProfileOffsetToPureOffset ipi_fiftyoneDegreesProfileOffsetToPureOffset
#define fiftyoneDegreesProfileReadFromFile ipi_fiftyoneDegreesProfileReadFromFile
#define fiftyoneDegreesPropertiesCreate ipi_fiftyoneDegreesPropertiesCreate
#define fiftyoneDegreesPropertiesDefault ipi_fiftyoneDegreesPropertiesDefault
#define fiftyoneDegreesPropertiesFree ipi_fiftyoneDegreesPropertiesFree
#define fiftyoneDegreesPropertiesGetNameFromRequiredIndex ipi_fiftyoneDegreesPropertiesGetNameFromRequiredIndex
#define fiftyoneDegreesPropertiesGetPropertyIndexFromName ipi_fiftyoneDegreesPropertiesGetPropertyIndexFromName
#define fiftyoneDegreesPropertiesGetPropertyIndexFromRequiredIndex ipi_fiftyoneDegreesPropertiesGetPropertyIndexFromRequiredIndex
#define fiftyoneDegreesPropertiesGetRequiredPropertyIndexFromName ipi_fiftyoneDegreesPropertiesGetRequiredPropertyIndexFromName
#define fiftyoneDegreesPropertiesIsSetHeaderAvailable ipi_fiftyoneDegreesPropertiesIsSetHeaderAvailable
#define fiftyoneDegreesPropertyGet ipi_fiftyoneDegreesPropertyGet
#define fiftyoneDegreesPropertyGetByName ipi_fiftyoneDegreesPropertyGetByName
#define fiftyoneDegreesPropertyGetCategory ipi_fiftyoneDegreesPropertyGetCategory
#define fiftyoneDegreesPropertyGetDescription ipi_fiftyoneDegreesPropertyGetDescription
#define fiftyoneDegreesPropertyGetName ipi_fiftyoneDegreesPropertyGetName
#define fiftyoneDegreesPropertyGetStoredType ipi_fiftyoneDegreesPropertyGetStoredType
#define fiftyoneDegreesPropertyGetStoredTypeByIndex ipi_fiftyoneDegreesPropertyGetStoredTypeByIndex
#define fiftyoneDegreesPropertyGetUrl ipi_fiftyoneDegreesPropertyGetUrl
#define fiftyoneDegreesPropertyGetValueType ipi_fiftyoneDegreesPropertyGetValueType
#define fiftyoneDegreesPropertyValueTypeGetUnderlyingType ipi_fiftyoneDegreesPropertyValueTypeGetUnderlyingType
#define fiftyoneDegreesResourceHandleDecUse ipi_fiftyoneDegreesResourceHandleDecUse
#define fiftyoneDegreesResourceHandleGetUse ipi_fiftyoneDegreesResourceHandleGetUse
#define fiftyoneDegreesResourceHandleIncUse ipi_fiftyoneDegreesResourceHandleIncUse
#define fiftyoneDegreesResourceManagerFree ipi_fiftyoneDegreesResourceManagerFree
#define fiftyoneDegreesResourceManagerInit ipi_fiftyoneDegreesResourceManagerInit
#define fiftyoneDegreesResourceReplace ipi_fiftyoneDegreesResourceReplace
#define fiftyoneDegreesResultsInit ipi_fiftyoneDegreesResultsInit
#define fiftyoneDegreesSetUpMemoryTracking ipi_fiftyoneDegreesSetUpMemoryTracking
#define fiftyoneDegreesSignalClose ipi_fiftyoneDegreesSignalClose
#define fiftyoneDegreesSignalCreate ipi_fiftyoneDegreesSignalCreate
#define fiftyoneDegreesSignalSet ipi_fiftyoneDegreesSignalSet
#define fiftyoneDegreesSignalWait ipi_fiftyoneDegreesSignalWait
#define fiftyoneDegreesStatusGetMessage ipi_fiftyoneDegreesStatusGetMessage
#define fiftyoneDegreesStoredBinaryValueCompareWithString ipi_fiftyoneDegreesStoredBinaryValueCompareWithString
#define fiftyoneDegreesStoredBinaryValueGet ipi_fiftyoneDegreesStoredBinaryValueGet
#define fiftyoneDegreesStoredBinaryValueRead ipi_fiftyoneDegreesStoredBinaryValueRead
#define fiftyoneDegreesStoredBinaryValueToBoolOrDefault ipi_fiftyoneDegreesStoredBinaryValueToBoolOrDefault
#define fiftyoneDegreesStoredBinaryValueToDoubleOrDefault ipi_fiftyoneDegreesStoredBinaryValueToDoubleOrDefault
#define fiftyoneDegreesStoredBinaryValueToIntOrDefault ipi_fiftyoneDegreesStoredBinaryValueToIntOrDefault
#define fiftyoneDegreesStringBuilderAddChar ipi_fiftyoneDegreesStringBuilderAddChar
#define fiftyoneDegreesStringBuilderAddChars ipi_fiftyoneDegreesStringBuilderAddChars
#define fiftyoneDegreesStringBuilderAddDouble ipi_fiftyoneDegreesStringBuilderAddDouble
#define fiftyoneDegreesStringBuilderAddInteger ipi_fiftyoneDegreesStringBuilderAddInteger
#define fiftyoneDegreesStringBuilderAddIpAddress ipi_fiftyoneDegreesStringBuilderAddIpAddress
#define fiftyoneDegreesStringBuilderAddStringValue ipi_fiftyoneDegreesStringBuilderAddStringValue
#define fiftyoneDegreesStringBuilderComplete ipi_fiftyoneDegreesStringBuilderComplete
#define fiftyoneDegreesStringBuilderInit ipi_fiftyoneDegreesStringBuilderInit
#define fiftyoneDegreesStringCompare ipi_fiftyoneDegreesStringCompare
#define fiftyoneDegreesStringCompareLength ipi_fiftyoneDegreesStringCompareLength
#define fiftyoneDegreesStringGet ipi_fiftyoneDegreesStringGet
#define fiftyoneDegreesStringGetFinalSize ipi_fiftyoneDegreesStringGetFinalSize
#define fiftyoneDegreesStringRead ipi_fiftyoneDegreesStringRead
#define fiftyoneDegreesStringSubString ipi_fiftyoneDegreesStringSubString
#define fiftyoneDegreesTextFileIterate ipi_fiftyoneDegreesTextFileIterate
#define fiftyoneDegreesTextFileIterateWithLimit ipi_fiftyoneDegreesTextFileIterateWithLimit
#define fiftyoneDegreesThreadingGetIsThreadSafe ipi_fiftyoneDegreesThreadingGetIsThreadSafe
#define fiftyoneDegreesThrowUnsupportedStoredValueType ipi_fiftyoneDegreesThrowUnsupportedStoredValueType
#define fiftyoneDegreesTreeCount ipi_fiftyoneDegreesTreeCount
#define fiftyoneDegreesTreeDelete ipi_fiftyoneDegreesTreeDelete
#define fiftyoneDegreesTreeFind ipi_fiftyoneDegreesTreeFind
#define fiftyoneDegreesTreeInsert ipi_fiftyoneDegreesTreeInsert
#define fiftyoneDegreesTreeIterateNodes ipi_fiftyoneDegreesTreeIterateNodes
#define fiftyoneDegreesTreeNodeInit ipi_fiftyoneDegreesTreeNodeInit
#define fiftyoneDegreesTreeNodeRemove ipi_fiftyoneDegreesTreeNodeRemove
#define fiftyoneDegreesTreeRootInit ipi_fiftyoneDegreesTreeRootInit
#define fiftyoneDegreesUnsetMemoryTracking ipi_fiftyoneDegreesUnsetMemoryTracking
#define fiftyoneDegreesValueGet ipi_fiftyoneDegreesValueGet
#define fiftyoneDegreesValueGetByName ipi_fiftyoneDegreesValueGetByName
#define fiftyoneDegreesValueGetByNameAndType ipi_fiftyoneDegreesValueGetByNameAndType
#define fiftyoneDegreesValueGetContent ipi_fiftyoneDegreesValueGetContent
#define fiftyoneDegreesValueGetDescription ipi_fiftyoneDegreesValueGetDescription
#define fiftyoneDegreesValueGetIndexByName ipi_fiftyoneDegreesValueGetIndexByName
#define fiftyoneDegreesValueGetIndexByNameAndType ipi_fiftyoneDegreesValueGetIndexByNameAndType
#define fiftyoneDegreesValueGetName ipi_fiftyoneDegreesValueGetName
#define fiftyoneDegreesValueGetUrl ipi_fiftyoneDegreesValueGetUrl
#define fiftyoneDegreesValueGetWeight ipi_fiftyoneDegreesValueGetWeight
#define fiftyoneDegreesValueIsWeighted ipi_fiftyoneDegreesValueIsWeighted
#define fiftyoneDegreesWeightedItemListAdd ipi_fiftyoneDegreesWeightedItemListAdd
#define fiftyoneDegreesWeightedItemListExtend ipi_fiftyoneDegreesWeightedItemListExtend
#define fiftyoneDegreesWeightedItemListFree ipi_fiftyoneDegreesWeightedItemListFree
#define fiftyoneDegreesWeightedItemListInit ipi_fiftyoneDegreesWeightedItemListInit
#define fiftyoneDegreesWeightedItemListRelease ipi_fiftyoneDegreesWeightedItemListRelease
#define fiftyoneDegreesWriteWkbAsWktToStringBuilder ipi_fiftyoneDegreesWriteWkbAsWktToStringBuilder
#define fiftyoneDegreesYamlFileIterate ipi_fiftyoneDegreesYamlFileIterate
#define fiftyoneDegreesYamlFileIterateWithLimit ipi_fiftyoneDegreesYamlFileIterateWithLimit

#endif /* FIFTYONE_DEGREES_IPI_SYMBOL_PREFIX_H */
