/* *********************************************************************
 * This Original Work is copyright of 51 Degrees Mobile Experts Limited.
 * Copyright 2026 51 Degrees Mobile Experts Limited, Davidson House,
 * Forbury Square, Reading, Berkshire, United Kingdom RG1 3EU.
 *
 * This Original Work is licensed under the European Union Public Licence
 * (EUPL) v.1.2 and is subject to its terms as set out below.
 *
 * If a copy of the EUPL was not distributed with this file, You can obtain
 * one at https://opensource.org/licenses/EUPL-1.2.
 *
 * The 'Compatible Licences' set out in the Appendix to the EUPL (as may be
 * amended by the European Commission) shall be deemed incompatible for
 * the purposes of the Work and the provisions of the compatibility
 * clause in Article 5 of the EUPL shall not apply.
 *
 * If using the Work as, or as part of, a network application, by
 * including the attribution notice(s) required under Article 5 of the EUPL
 * in the end user terms of the application under an appropriate heading,
 * such notice(s) shall fulfill the requirements of that article.
 * ********************************************************************* */

//! The per-request tower middleware.
//!
//! [`fiftyone_middleware`] is written for [`axum::middleware::from_fn_with_state`].
//! For each request it:
//!
//! 1. **Short-circuits the two client-side endpoints.** A `GET` to the
//!    JavaScript path or a `POST` to the JSON path is served directly by the
//!    endpoint handlers, because those responses are wholly generated by the
//!    pipeline and never reach the application's own routes.
//! 2. **Processes the pipeline** for every other request (off the async runtime,
//!    see [`crate::process`]), then stores the processed flow data in the request
//!    extensions as a [`FiftyOneResult`] so a downstream handler can read it
//!    through the extractor.
//! 3. **Calls the next layer** and, on the way back out, **applies the
//!    set-headers output**: every response header the set-headers element asked
//!    for is appended to the response (joined with the HTTP list separator when
//!    a header is already present).
//!
//! Install it with [`crate::register`], or directly:
//!
//! ```no_run
//! use std::sync::Arc;
//! use axum::{middleware::from_fn_with_state, Router};
//! use fiftyone_pipeline_web::{WebIntegrationOptions, WebPipeline};
//! use fiftyone_pipeline_web_axum::{fiftyone_middleware, FiftyOneState};
//!
//! # fn build() -> Router {
//! # let web = WebPipeline::build(Vec::new(), WebIntegrationOptions::default()).unwrap();
//! let state = FiftyOneState::from_web_pipeline(&web);
//! Router::new().layer(from_fn_with_state(state.clone(), fiftyone_middleware))
//! # }
//! ```

use axum::body::Body;
use axum::extract::State;
use axum::http::{HeaderName, HeaderValue, Method, Request};
use axum::middleware::Next;
use axum::response::Response;
use fiftyone_pipeline_web::{response_headers, WebEndpoint};

use crate::handlers::{javascript_handler, json_handler};
use crate::process::{process_request, CapturedRequest};
use crate::result::FiftyOneResult;
use crate::state::FiftyOneState;

/// The 51Degrees per-request middleware.
///
/// See the module documentation for what it does. Register it with
/// [`axum::middleware::from_fn_with_state`], passing a [`FiftyOneState`] as the
/// state, or use [`crate::register`].
pub async fn fiftyone_middleware(
    State(state): State<FiftyOneState>,
    request: Request<Body>,
    next: Next,
) -> Response {
    // 1. Short-circuit the client-side endpoints to their dedicated handlers.
    if let Some(endpoint) = client_side_endpoint(&state, &request) {
        return match endpoint {
            WebEndpoint::JavaScript => javascript_handler(State(state), request).await,
            WebEndpoint::Json => json_handler(State(state), request).await,
        };
    }

    // 2. Process the pipeline for every other request. A non-endpoint request
    // has no relevant body, so the form body is empty.
    let captured = CapturedRequest {
        headers: request.headers().clone(),
        uri: request.uri().clone(),
        body: Vec::new(),
        peer_addr: request
            .extensions()
            .get::<axum::extract::ConnectInfo<std::net::SocketAddr>>()
            .map(|connect_info| connect_info.0),
    };

    let flow_data = match process_request(&state, captured).await {
        Ok(flow_data) => flow_data,
        Err(_) => {
            // A panic in processing must not take the whole request down; pass it
            // through to the application without 51Degrees results.
            return next.run(request).await;
        }
    };

    // Read the set-headers output before the flow data is moved into the result
    // handle and locked away for the downstream handler.
    let set_headers = response_headers(&flow_data);

    // 3. Stash the processed flow data for the extractor, then run the rest of
    // the stack.
    let mut request = request;
    request
        .extensions_mut()
        .insert(FiftyOneResult::new(flow_data));
    let mut response = next.run(request).await;

    // 4. Append the set-headers output onto the response on the way out.
    apply_set_headers_to_response(&mut response, &set_headers);

    response
}

/// Decide whether a request targets a client-side endpoint, matching both the
/// path and the HTTP method the endpoint uses.
///
/// The JavaScript endpoint is a `GET` and the JSON endpoint is a `POST`. A path
/// that matches an endpoint but uses a different method is not treated as that
/// endpoint, so (for example) a `GET` to the JSON path falls through to the
/// application rather than being served an empty JSON callback.
fn client_side_endpoint(state: &FiftyOneState, request: &Request<Body>) -> Option<WebEndpoint> {
    match state.endpoint_for(request.uri().path()) {
        Some(WebEndpoint::JavaScript) if request.method() == Method::GET => {
            Some(WebEndpoint::JavaScript)
        }
        Some(WebEndpoint::Json) if request.method() == Method::POST => Some(WebEndpoint::Json),
        _ => None,
    }
}

/// Append the set-headers element's response headers onto an axum response.
///
/// For each `(name, value)` the element produced, the value is appended to the
/// existing values for that header (axum keeps each as a separate header line,
/// which is the wire-equivalent of a comma-joined list), or added fresh when the
/// header is absent. An empty value, or a name or value axum rejects, is skipped.
fn apply_set_headers_to_response(response: &mut Response, to_set: &[(String, String)]) {
    let headers = response.headers_mut();
    for (name, value) in to_set {
        if value.is_empty() {
            continue;
        }
        if let (Ok(name), Ok(value)) = (
            HeaderName::from_bytes(name.as_bytes()),
            HeaderValue::from_str(value),
        ) {
            // append (not insert) so a value the application already set for this
            // header is preserved alongside the 51Degrees one.
            headers.append(name, value);
        }
    }
}
