/* *********************************************************************
 * This Original Work is copyright of 51 Degrees Mobile Experts Limited.
 * Copyright 2026 51 Degrees Mobile Experts Limited, Davidson House,
 * Forbury Square, Reading, Berkshire, United Kingdom RG1 3EU.
 *
 * This Original Work is licensed under the European Union Public Licence
 * (EUPL) v.1.2 and is subject to its terms as set out below.
 *
 * If a copy of the EUPL was not distributed with this file, You can obtain
 * one at https://opensource.org/licenses/EUPL-1.2.
 *
 * The 'Compatible Licences' set out in the Appendix to the EUPL (as may be
 * amended by the European Commission) shall be deemed incompatible for
 * the purposes of the Work and the provisions of the compatibility
 * clause in Article 5 of the EUPL shall not apply.
 *
 * If using the Work as, or as part of, a network application, by
 * including the attribution notice(s) required under Article 5 of the EUPL
 * in the end user terms of the application under an appropriate heading,
 * such notice(s) shall fulfill the requirements of that article.
 * ********************************************************************* */

/* *********************************************************************
 * This code is auto generated by 51Degrees using the most up to data
 * at the time of release, and should not be changed directly.
 * **********************************************************************/

//! Generated strongly-typed read accessors for IP Intelligence.
//!
//! This file is produced by the 51Degrees PropertyGenerator tool from the
//! common metadata. It defines the [`IpIntelligenceData`] trait, one accessor
//! per documented property, and implements it for the hand-written
//! [`IpIntelligenceDataBase`] by delegating to its by-name stores. Plain
//! properties resolve to a single typed value; the weighted properties
//! (the country-code distributions and `Mcc`) resolve to an ordered list of
//! weighted candidates.
#![allow(rustdoc::bare_urls, rustdoc::invalid_html_tags)]

use crate::data::IpIntelligenceDataBase;
use fiftyone_pipeline_core::{PropertyValueType, WeightedValue};
use fiftyone_pipeline_engines::{AspectData, AspectPropertyValue};

/// Strongly-typed read accessors for IP Intelligence properties.
///
/// Covers the network and location properties of an IP. Each accessor
/// returns an [`AspectPropertyValue`] wrapping the property's value type, so
/// an absent value carries the engine's no-value reason.
pub trait IpIntelligenceData: AspectData {
    /// Radius in kilometers of the circle centred around the most probable location that encompasses the entire area. Where multiple areas are returned, this will only cover the area the most probable location is in. See Areas property. This will likely be a very large distance. It is recommend to use the AccuracyRadiusMin property.
    fn accuracy_radius_max(&self) -> AspectPropertyValue<i32>;

    /// Radius in kilometers of the largest circle centred around the most probable location that fits within the area. Where multiple areas are returned, only the area that the most probable location falls within is considered. See Areas property.
    fn accuracy_radius_min(&self) -> AspectPropertyValue<i32>;

    /// Any shapes associated with the location. Usually this is the area which the IP range covers. This is returned as a WKT String stored as a reduced format of WKB.
    fn areas(&self) -> AspectPropertyValue<String>;

    /// Autonomous System Number associated with the IP address.
    fn asn(&self) -> AspectPropertyValue<String>;

    /// The name registered to the Asn associated with the IP address.
    fn asn_name(&self) -> AspectPropertyValue<String>;

    /// Refers to the diversity of browsers observed from the IP range. An integer between 1-10, a lower value indicates a low number of browsers seen per IP address, while a higher value indicates a high number of browsers seen per IP address. A 0 value indicates that the probability is unknown.
    fn browser_diversity(&self) -> AspectPropertyValue<i32>;

    /// Indicates the type of connection being used. Returns either Broadband, Cellular, or Hosting and Anonymous.
    fn connection_type(&self) -> AspectPropertyValue<String>;

    /// The 3-character ISO 3166-1 continent code for the supplied location.
    fn continent_code2(&self) -> AspectPropertyValue<String>;

    /// The name of the continent the supplied location is in.
    fn continent_name(&self) -> AspectPropertyValue<String>;

    /// The name of the country that the supplied location is in.
    fn country(&self) -> AspectPropertyValue<String>;

    /// The 2-character ISO 3166-1 code of the country that the supplied location is in.
    fn country_code(&self) -> AspectPropertyValue<String>;

    /// The 3-character ISO 3166-1 alpha-3 code of the country that the supplied location is in.
    fn country_code3(&self) -> AspectPropertyValue<String>;

    /// A list of countries in ISO 3166-1 alpha-2 country code format that overlap with the area likely associated with the provided evidence, weighted and ordered by each country's proportion of the area. Administrative areas that cannot be cleanly resolved to the country level will not contribute to the resulting data.
    fn country_codes_geographical(&self) -> AspectPropertyValue<Vec<WeightedValue<String>>>;

    /// A list of countries in ISO 3166-1 alpha-2 country code format that overlap with the area likely associated with the provided evidence, weighted and ordered by each country's proportion of the total population within the area. Administrative areas that cannot be cleanly resolved to the country level will not contribute to the resulting data.
    fn country_codes_population(&self) -> AspectPropertyValue<Vec<WeightedValue<String>>>;

    /// The name of the county that the supplied location is in. In this case, a county is defined as an administrative sub-section of a country or state.
    fn county(&self) -> AspectPropertyValue<String>;

    /// The Alpha-3 ISO 4217 code of the currency associated with the supplied location.
    fn currency_code(&self) -> AspectPropertyValue<String>;

    /// ITU international telephone numbering plan code for the country.
    fn dial_code(&self) -> AspectPropertyValue<String>;

    /// Refers to the diversity of hardware devices observed from the IP range. An integer between 1-10, a lower value indicates a low number of devices seen per IP address, while a higher value indicates a high number of devices seen per IP address. A 0 value indicates that the probability is unknown.
    fn hardware_diversity(&self) -> AspectPropertyValue<i32>;

    /// The confidence that the IP address is a human user versus associated with hosting. A 0-10 value where; 0-3: Low confidence the user is human, 4-6: Medium confidence, 7-10: High confidence. A -1 value indicates that the probability is unknown.
    fn human_probability(&self) -> AspectPropertyValue<i32>;

    /// The IPv4 address of the request.
    fn ip(&self) -> AspectPropertyValue<String>;

    /// End of the IP range to which the evidence IP belongs.
    fn ip_range_end(&self) -> AspectPropertyValue<String>;

    /// Start of the IP range to which the evidence IP belongs.
    fn ip_range_start(&self) -> AspectPropertyValue<String>;

    /// The IPv6 address of the request.
    fn ip_v6(&self) -> AspectPropertyValue<String>;

    /// Indicates whether the IP address is associated with a broadband connection. Includes DSL, Cable, Fibre, and Satellite connections.
    fn is_broadband(&self) -> AspectPropertyValue<bool>;

    /// Indicates whether the IP address is associated with a cellular network.
    fn is_cellular(&self) -> AspectPropertyValue<bool>;

    /// Indicates whether the country of the supplied location is within the European Union.
    fn is_eu(&self) -> AspectPropertyValue<bool>;

    /// Indicates whether the IP address is associated with hosting. Includes both hosting and anonymised connections such as hosting networks, hosting ASNs, VPNs, proxies, TOR networks, and unreachable IP addresses.
    fn is_hosted(&self) -> AspectPropertyValue<bool>;

    /// The ISO 3166-2 code for the supplied location. This is using the 'ISO3166-2-lvl4' property from OpenStreetMap.
    fn iso31662_lvl4(&self) -> AspectPropertyValue<String>;

    /// The alphanumeric code representing the subdivision from the ISO 3166-2 code of the supplied location. This is using the 'ISO3166-2-lvl4' property from OpenStreetMap.
    fn iso31662_lvl4_subdivision_only(&self) -> AspectPropertyValue<String>;

    /// The ISO 3166-2 code for the supplied location. This is using the 'ISO3166-2-lvl8' property from OpenStreetMap.
    fn iso31662_lvl8(&self) -> AspectPropertyValue<String>;

    /// The alphanumeric code representing the subdivision from the ISO 3166-2 code of the supplied location. This is using the 'ISO3166-2-lvl8' property from OpenStreetMap.
    fn iso31662_lvl8_subdivision_only(&self) -> AspectPropertyValue<String>;

    /// Indicates whether the IP address is associated with a Proxy server.
    fn is_proxy(&self) -> AspectPropertyValue<bool>;

    /// Indicates whether the IP address is associated with a public router.
    fn is_public_router(&self) -> AspectPropertyValue<bool>;

    /// Indicates whether the IP address is associated with a TOR server.
    fn is_tor(&self) -> AspectPropertyValue<bool>;

    /// Indicates whether the IP address is associated with a VPN server.
    fn is_vpn(&self) -> AspectPropertyValue<bool>;

    /// The Alpha-2 ISO 639 Language code associated with the supplied location.
    fn language_code(&self) -> AspectPropertyValue<String>;

    /// Average latitude of the IP. For privacy, this is randomized within around 1 kilometer of the result. Randomized result will change only once per day.
    fn latitude(&self) -> AspectPropertyValue<f32>;

    /// The confidence in the town and country provided.
    fn location_confidence(&self) -> AspectPropertyValue<String>;

    /// Average longitude of the IP. For privacy, this is randomized within around 1 kilometer of the result. Randomized result will change only once per day.
    fn longitude(&self) -> AspectPropertyValue<f32>;

    /// The mobile country code of the network the device is connected to.
    fn mcc(&self) -> AspectPropertyValue<Vec<WeightedValue<String>>>;

    /// Refers to the diversity of software observed from the IP range. An integer between 1-10, a lower value indicates a low number of software seen per IP address, while a higher value indicates a high number of software seen per IP address. A 0 value indicates that the probability is unknown.
    fn platform_diversity(&self) -> AspectPropertyValue<i32>;

    /// The name of the geographical region that the supplied location is in.
    fn region(&self) -> AspectPropertyValue<String>;

    /// Country code of the registered range.
    fn registered_country(&self) -> AspectPropertyValue<String>;

    /// Name of the IP range. This is usually the owner.
    fn registered_name(&self) -> AspectPropertyValue<String>;

    /// Registered owner of the range.
    fn registered_owner(&self) -> AspectPropertyValue<String>;

    /// The name of the state that the supplied location is in.
    fn state(&self) -> AspectPropertyValue<String>;

    /// The name of the suburb that the supplied location is in.
    fn suburb(&self) -> AspectPropertyValue<String>;

    /// The time zone at the supplied location in the IANA Time Zone format.
    fn time_zone_iana(&self) -> AspectPropertyValue<String>;

    /// The offset from UTC in minutes in the supplied location, at the time that the value is produced.
    fn time_zone_offset(&self) -> AspectPropertyValue<i32>;

    /// The name of the town that the supplied location is in.
    fn town(&self) -> AspectPropertyValue<String>;

    /// The zip or postal code that the supplied location falls under.
    fn zip_code(&self) -> AspectPropertyValue<String>;
}

impl IpIntelligenceData for IpIntelligenceDataBase {
    fn accuracy_radius_max(&self) -> AspectPropertyValue<i32> {
        self.integer("AccuracyRadiusMax")
    }

    fn accuracy_radius_min(&self) -> AspectPropertyValue<i32> {
        self.integer("AccuracyRadiusMin")
    }

    fn areas(&self) -> AspectPropertyValue<String> {
        self.string("Areas")
    }

    fn asn(&self) -> AspectPropertyValue<String> {
        self.string("Asn")
    }

    fn asn_name(&self) -> AspectPropertyValue<String> {
        self.string("AsnName")
    }

    fn browser_diversity(&self) -> AspectPropertyValue<i32> {
        self.integer("BrowserDiversity")
    }

    fn connection_type(&self) -> AspectPropertyValue<String> {
        self.string("ConnectionType")
    }

    fn continent_code2(&self) -> AspectPropertyValue<String> {
        self.string("ContinentCode2")
    }

    fn continent_name(&self) -> AspectPropertyValue<String> {
        self.string("ContinentName")
    }

    fn country(&self) -> AspectPropertyValue<String> {
        self.string("Country")
    }

    fn country_code(&self) -> AspectPropertyValue<String> {
        self.string("CountryCode")
    }

    fn country_code3(&self) -> AspectPropertyValue<String> {
        self.string("CountryCode3")
    }

    fn country_codes_geographical(&self) -> AspectPropertyValue<Vec<WeightedValue<String>>> {
        self.weighted_string("CountryCodesGeographical")
    }

    fn country_codes_population(&self) -> AspectPropertyValue<Vec<WeightedValue<String>>> {
        self.weighted_string("CountryCodesPopulation")
    }

    fn county(&self) -> AspectPropertyValue<String> {
        self.string("County")
    }

    fn currency_code(&self) -> AspectPropertyValue<String> {
        self.string("CurrencyCode")
    }

    fn dial_code(&self) -> AspectPropertyValue<String> {
        self.string("DialCode")
    }

    fn hardware_diversity(&self) -> AspectPropertyValue<i32> {
        self.integer("HardwareDiversity")
    }

    fn human_probability(&self) -> AspectPropertyValue<i32> {
        self.integer("HumanProbability")
    }

    fn ip(&self) -> AspectPropertyValue<String> {
        self.string("Ip")
    }

    fn ip_range_end(&self) -> AspectPropertyValue<String> {
        self.string("IpRangeEnd")
    }

    fn ip_range_start(&self) -> AspectPropertyValue<String> {
        self.string("IpRangeStart")
    }

    fn ip_v6(&self) -> AspectPropertyValue<String> {
        self.string("IpV6")
    }

    fn is_broadband(&self) -> AspectPropertyValue<bool> {
        self.boolean("IsBroadband")
    }

    fn is_cellular(&self) -> AspectPropertyValue<bool> {
        self.boolean("IsCellular")
    }

    fn is_eu(&self) -> AspectPropertyValue<bool> {
        self.boolean("IsEu")
    }

    fn is_hosted(&self) -> AspectPropertyValue<bool> {
        self.boolean("IsHosted")
    }

    fn iso31662_lvl4(&self) -> AspectPropertyValue<String> {
        self.string("Iso31662Lvl4")
    }

    fn iso31662_lvl4_subdivision_only(&self) -> AspectPropertyValue<String> {
        self.string("Iso31662Lvl4SubdivisionOnly")
    }

    fn iso31662_lvl8(&self) -> AspectPropertyValue<String> {
        self.string("Iso31662Lvl8")
    }

    fn iso31662_lvl8_subdivision_only(&self) -> AspectPropertyValue<String> {
        self.string("Iso31662Lvl8SubdivisionOnly")
    }

    fn is_proxy(&self) -> AspectPropertyValue<bool> {
        self.boolean("IsProxy")
    }

    fn is_public_router(&self) -> AspectPropertyValue<bool> {
        self.boolean("IsPublicRouter")
    }

    fn is_tor(&self) -> AspectPropertyValue<bool> {
        self.boolean("IsTor")
    }

    fn is_vpn(&self) -> AspectPropertyValue<bool> {
        self.boolean("IsVPN")
    }

    fn language_code(&self) -> AspectPropertyValue<String> {
        self.string("LanguageCode")
    }

    fn latitude(&self) -> AspectPropertyValue<f32> {
        self.float("Latitude")
    }

    fn location_confidence(&self) -> AspectPropertyValue<String> {
        self.string("LocationConfidence")
    }

    fn longitude(&self) -> AspectPropertyValue<f32> {
        self.float("Longitude")
    }

    fn mcc(&self) -> AspectPropertyValue<Vec<WeightedValue<String>>> {
        self.weighted_string("Mcc")
    }

    fn platform_diversity(&self) -> AspectPropertyValue<i32> {
        self.integer("PlatformDiversity")
    }

    fn region(&self) -> AspectPropertyValue<String> {
        self.string("Region")
    }

    fn registered_country(&self) -> AspectPropertyValue<String> {
        self.string("RegisteredCountry")
    }

    fn registered_name(&self) -> AspectPropertyValue<String> {
        self.string("RegisteredName")
    }

    fn registered_owner(&self) -> AspectPropertyValue<String> {
        self.string("RegisteredOwner")
    }

    fn state(&self) -> AspectPropertyValue<String> {
        self.string("State")
    }

    fn suburb(&self) -> AspectPropertyValue<String> {
        self.string("Suburb")
    }

    fn time_zone_iana(&self) -> AspectPropertyValue<String> {
        self.string("TimeZoneIana")
    }

    fn time_zone_offset(&self) -> AspectPropertyValue<i32> {
        self.integer("TimeZoneOffset")
    }

    fn town(&self) -> AspectPropertyValue<String> {
        self.string("Town")
    }

    fn zip_code(&self) -> AspectPropertyValue<String> {
        self.string("ZipCode")
    }
}

/// Every generated property paired with its core value type, in name
/// order. The data base uses this to publish per-property metadata.
pub const GENERATED_PROPERTY_TYPES: &[(&str, PropertyValueType)] = &[
    ("AccuracyRadiusMax", PropertyValueType::Integer),
    ("AccuracyRadiusMin", PropertyValueType::Integer),
    ("Areas", PropertyValueType::String),
    ("Asn", PropertyValueType::String),
    ("AsnName", PropertyValueType::String),
    ("BrowserDiversity", PropertyValueType::Integer),
    ("ConnectionType", PropertyValueType::String),
    ("ContinentCode2", PropertyValueType::String),
    ("ContinentName", PropertyValueType::String),
    ("Country", PropertyValueType::String),
    ("CountryCode", PropertyValueType::String),
    ("CountryCode3", PropertyValueType::String),
    ("CountryCodesGeographical", PropertyValueType::KeyValueList),
    ("CountryCodesPopulation", PropertyValueType::KeyValueList),
    ("County", PropertyValueType::String),
    ("CurrencyCode", PropertyValueType::String),
    ("DialCode", PropertyValueType::String),
    ("HardwareDiversity", PropertyValueType::Integer),
    ("HumanProbability", PropertyValueType::Integer),
    ("Ip", PropertyValueType::String),
    ("IpRangeEnd", PropertyValueType::String),
    ("IpRangeStart", PropertyValueType::String),
    ("IpV6", PropertyValueType::String),
    ("IsBroadband", PropertyValueType::Bool),
    ("IsCellular", PropertyValueType::Bool),
    ("IsEu", PropertyValueType::Bool),
    ("IsHosted", PropertyValueType::Bool),
    ("Iso31662Lvl4", PropertyValueType::String),
    ("Iso31662Lvl4SubdivisionOnly", PropertyValueType::String),
    ("Iso31662Lvl8", PropertyValueType::String),
    ("Iso31662Lvl8SubdivisionOnly", PropertyValueType::String),
    ("IsProxy", PropertyValueType::Bool),
    ("IsPublicRouter", PropertyValueType::Bool),
    ("IsTor", PropertyValueType::Bool),
    ("IsVPN", PropertyValueType::Bool),
    ("LanguageCode", PropertyValueType::String),
    ("Latitude", PropertyValueType::Double),
    ("LocationConfidence", PropertyValueType::String),
    ("Longitude", PropertyValueType::Double),
    ("Mcc", PropertyValueType::KeyValueList),
    ("PlatformDiversity", PropertyValueType::Integer),
    ("Region", PropertyValueType::String),
    ("RegisteredCountry", PropertyValueType::String),
    ("RegisteredName", PropertyValueType::String),
    ("RegisteredOwner", PropertyValueType::String),
    ("State", PropertyValueType::String),
    ("Suburb", PropertyValueType::String),
    ("TimeZoneIana", PropertyValueType::String),
    ("TimeZoneOffset", PropertyValueType::Integer),
    ("Town", PropertyValueType::String),
    ("ZipCode", PropertyValueType::String),
];
